################################## server port ##################################
server:
  port: 8081
  servlet:
    contextPath: /api/v1/token/client
  
################################# database config ################################
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: token-db
  
################################ springdoc config ################################
springdoc:
  packagesToScan: com.techsophy.tstokens
  pathsToMatch: /**

################################ security config ################################
user:
  oauth:
    clientId: devglan-client
    clientSecret: devglan-secret
    redirectUris: http://localhost:8081/login
    user.username: sanjay@techsophy.com
    user.password: sanjay
    accessTokenValidity: 1440000
    refreshTokenValidity: 2000000
    cookieName: token-cookie
security:
  oauth2:
    resource:
      filter-order: 3